language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: "Build, test and release"
      before_script:
        - npm run test:unit
      script:
        - npm run build
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - npm run release